### ISSUE TITLE
DoctrineParamConverter skips mapped fields that don't exist without error

### ISSUE THREAD

**Issue by ruudk** [sensiolabs/SensioFrameworkExtraBundle#235]
The DoctrineParamConverter has the ability to map route parameters to doctrine fields. But when you map a route parameter to a non-existing field it won't throw an error, it just skips it as a criteria.

When you have a Page entity (id, slug) you can do the following:

``` php
@Route("/show/{page_id}/{page_slug}")
@ParamConverter("page", class="AppBundle:Page", options={
    "mapping" = {
        "page_id"   = "id", 
        "page_slug" = "slug"
    }
})
```

When you open `/show/50/contact` the DoctrineParamConverter will execute it like this:

``` php
$em->getRepository('AppBundle:Page')-> findOneBy(array(
    'id'   => '50',
    'slug' => 'contact'
));
```

But what happens when you make a mistake in the `mapping` declaration? In the mapping I typed `not_existing_field` for the `page_slug` route parameter:

``` php
@Route("/show/{page_id}/{page_slug}")
@ParamConverter("page", class="AppBundle:Page", options={
    "mapping" = {
        "page_id"   = "id", 
        "page_slug" = "not_existing_field"
    }
})
```

When you open `/show/50/contact` the DoctrineParamConverter will execute it like this:

``` php
$em->getRepository('AppBundle:Page')->findOneBy(array(
    'id' => '50'
));
```

This doesn't seem right.

The problem is in this code: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Request/ParamConverter/DoctrineParamConverter.php#L140:L144

**Comment by lars-feyerabend** [comment]
How has this issue been ignored for over 3 years? In my opinion, this is a major security issue. Example are composite keys, where one is, e.g., a user reference and one is some other identifier. If I misspelled the mapping for my user reference, I would potentially leak some other users' data here, because the query would only match the second parameter.

I think the DoctrineParamConverter should throw an exception upon encountering an invalid mapped field to let the developer know of their mistake.
