### ISSUE TITLE
garbage collection issue with 3.0.13

### ISSUE THREAD

**Issue by craue** [sensiolabs/SensioFrameworkExtraBundle#402]
After updating this bundle from 3.0.12 to 3.0.13 in a project, its test suite errors with `Doctrine\DBAL\Exception\DriverException: An exception occured in driver: SQLSTATE[HY000] [1040] Too many connections` after some time, so I guess there's an issue with garbage collection now. When [comparing 3.0.12 and 3.0.13](https://github.com/sensiolabs/SensioFrameworkExtraBundle/compare/v3.0.12...v3.0.13), the only code-relevant changes are in #391. Happens at least with Symfony 2.6.13 and 2.7.9.

**Comment by iltar** [comment]
The only difference I can imagine that might cause this: https://github.com/sensiolabs/SensioFrameworkExtraBundle/compare/v3.0.12...v3.0.13#diff-b1ccf35ef630c011c0f4275f4b322084R172

This is a property in the annotation, which is stored in the request.

**Comment by stof** [comment]
This will indeed store the controller (and so the container) inside the annotation object, which might cause issues (also for caching btw).

**Comment by iltar** [comment]
By default nothing is cached, see symfony/symfony/pull/17933. For that solution I will remove it from the Template annotation because it's no longer needed as I will be able to just fetch the information based on the controller/action.

Running this version in production since it got released and haven't found any issues yet. Maybe I'm not hitting the case that triggers this issue.

**Comment by stof** [comment]
@iltar but annotations are cached, and Template is an annotation object

**Comment by iltar** [comment]
@stof does it write the annotation back into the cache if it changes contextually?

**Comment by stof** [comment]
@iltar it might be saved again depending on what happens (although I'm not sure about the code path which could actually trigger it, it might even depend on the cache implementation). This is the issue with mutable objects: the caching becomes much harder when you mutate them after reading the cache. Storing this info in the annotation objects looks like a bad idea to me (this objects will outlive the scope where you need the value by far due to the caching)

**Comment by iltar** [comment]
Hm I think the quickfix would be to unset the owner in the second part of the listener, I'll write a patch tomorrow.
