### ISSUE TITLE
kernel.controller event listeners order

### ISSUE THREAD

**Issue by Gorjunov** [sensiolabs/SensioFrameworkExtraBundle#465]
I'm working on creating API and for authentication I'm using WSSE authentication (http://symfony.com/doc/current/security/custom_authentication_provider.html). I use `@ParamConverter` annotation to convert and validate requests. On testing process I've found, that `Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener` executes before `Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener` what is in my opinion strange - no need to parse all request and validate it if client has no permission to use it. (At least it looks strange for `stateless` firewall).

Is there any reason why listeners run in this order? If no, then it would be nice to have some configuration to set order of listeners. (I tried to do it, but looks like there is no way to add config to EventSubscriber)

**Comment by jvasseur** [comment]
The reason the run in this order is to allow using values resolved by the param converters in the security expression.

This allow to do something like this:
```php
/**
 * @ParamConverter("foo")
 * @Security("is_granted('view', foo)")
 */
```

Making them configurable is not a good option because it will break bundles that assume the current order. But if you want to hack around it, you could replace the event subscriber with explicit event listeners to replace the priority.

**Comment by jakzal** [comment]
Closing as @jvasseur perfectly explained why it's implemented this way.
