### ISSUE TITLE
DoctrineParamConverter throws logic exception

### ISSUE THREAD

**Issue by motivatedsloth** [sensiolabs/SensioFrameworkExtraBundle#472]
The DoctrineParamConverter throws a logic exception when it is unable find an object. 
The example on this page will always throw the exception: [https://symfony.com/doc/current/controller/argument_value_resolver.html](https://symfony.com/doc/current/controller/argument_value_resolver.html)
The problem is that the DoctrineParamConverter will attempt to convert any type-hinted controller argument that is a doctrine entity. Even if there are no parameters in the route.
That means it is impossible to write an ArgumentValueResolver for a doctrine entity.
It is possible to write a custom ParamConverter but it will only be executed if is registered with a higher priority than the DoctrineParamConverter.
I think it would be better the DoctrineParamConverter::supports() would return false instead of throwing an exception in the DoctrineParamConverter::apply(). I realize making that work would involve changing the method signature to accept the Request object.

**Comment by iltar** [comment]
Personally I would rather have the doctrine parameter converter disabled completely, as it gets affected by other arguments in the method. These kind of side effects nearly broke my application without knowing it.

**Comment by davidbarratt** [comment]
To give some more details to this issue.

If you have a route like this:
https://github.com/geosocio/core/blob/31975fe37af3a47054d2aa3f82757407893eb8e2/src/Controller/UserController.php#L141-L163

and you have an Argument Resolver like this:
https://github.com/geosocio/core/blob/31975fe37af3a47054d2aa3f82757407893eb8e2/src/ArgumentResolver/AuthenticatedUserResolver.php

You will get this exception:
> Unable to guess how to get a Doctrine instance from the request information for parameter "authenticated".

This happens because `ParamConverterListener` uses the `KernelEvents::CONTROLLER` event:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v3.0.25/EventListener/ParamConverterListener.php#L126

However, that event is fired **before** the arguments are resolved:
https://github.com/symfony/symfony/blob/v3.2.7/src/Symfony/Component/HttpKernel/HttpKernel.php#L140-L145

Perhaps it would be better for the `ParamConverter` to either be an Argument Resolver (which would allow users to reorder their resolver in relation to `ParamConverter`) or for it to use `KernelEvents::CONTROLLER_ARGUMENTS` (which comes after argument resolving)?

**Comment by davidbarratt** [comment]
If you need a workaround to this issue, add something like this to your config:
https://github.com/geosocio/core/blob/bb0cfcecda1e90987cd23ff197caffd15990384e/app/config/config.yml#L24-L27

Then you'll need to explicitly add the convertor everywhere you need it:
https://github.com/geosocio/core/blob/bb0cfcecda1e90987cd23ff197caffd15990384e/src/Controller/UserController.php#L146

Not ideal, but it does get around this issue.

I got all this from this page:
http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html

**Comment by iltar** [comment]
> Perhaps it would be better for the ParamConverter to either be an Argument Resolver (which would allow users to reorder their resolver in relation to ParamConverter) or for it to use `KernelEvents::CONTROLLER_ARGUMENTS` (which comes after argument resolving)?

See #436

**Comment by davidbarratt** [comment]
I created another argument resolver and ran into the same issue. _sigh_
https://github.com/geosocio/http-serializer/blob/develop/src/ArgumentResolver/ContentClassResolver.php

**Comment by iltar** [comment]
I've ran into this issue as well, I'm thinking of just turning the doctrine version off, it's just magic and useless for me.

**Comment by skornev** [comment]
I have the same issue. I agree with Iltar that it would be better to turn off this feature as default converter. 
It should be explicitly set to turn Doctrine converter for specified variables. 
As motivatedsloth  has already told, currently there is no way to enable a custom controller without  registering it  with a higher priority than the DoctrineParamConverter. 
Priority="false" also does not help

**Comment by skornev** [comment]
I think a quick solution would be to disable calling other default converters  for  a explicitly set converter or at least when  priority="false" ,
That would not break BC.

**Comment by fabpot** [comment]
see #511

**Comment by fabpot** [comment]
Closing as #511 allows to disable Doctrine altogether, and then adding explicit @ParamConverter is still possible when you want it.
