### ISSUE TITLE
BC break in Method annotation

### ISSUE THREAD

**Issue by garak** [sensiolabs/SensioFrameworkExtraBundle#515]
Until version 3, this was working:
```
    /** 
     * @Route("", name="foo")
     * @Method("GET")
     */
    public function fooAction()
    {   
    }   
```

After upgrading to version 4, this stopped working, and the route has no method set (not even "ANY"), causing a `MethodNotAllowedHttpException`.
I had to change any of such annotation with `@Method({"GET"})`

I'm fine with such change, but I think it should be mentioned as BC in changelog

Edit: also this stopped working `@Method({"GET", "POST"})`. Now it needs to be `@Method({"GET","POST"})` (without space)

**Comment by fabpot** [comment]
Looks like a bug to me.

**Comment by fabpot** [comment]
@garak Do you have time to have a look at why this is now required to pass an array?

**Comment by garak** [comment]
Sure, I'll do ASAP

**Comment by weaverryan** [comment]
@garak I just tried this quickly locally by using the `master` branch, and I couldn't repeat either issue :/.  Everything seemed to work just fine.... which is weird :). Did you find out any more?

**Comment by xabbuh** [comment]
Did both tries use the same version of the `doctrine/annotations` package?

**Comment by weaverryan** [comment]
I'm debugging it now. And yea, I was able to repeat this on symfony-demo by ONLY upgrading the FWExtraBundle. I think I found the problem...

**Comment by weaverryan** [comment]
The problem is this: https://github.com/sensiolabs/SensioFrameworkExtraBundle/compare/v3.0.27...v4.0.0#diff-c008b6d6230c590eb2e776909c1d9c07R27 the `protected` to `private` change.

For some reason (because the `__construct()` method is in the parent class?, which calls `setValues()` which ultimately sets this?), this results in the *private* `$methods` remaining empty, and a new *protected* `$methods` having the correct value (literally, if you `var_dump`, you see both a private and protected `$methods` property). Then, when `AnnotatedRouteControllerLoader` calls `->getMethods()`, it gets the private (so empty) property back.

But it gets stranger. I was able to repeat this exactly as mentioned. But, I am not able to repeat it in the SensioFrameworkExtraBundle tests. And now suddenly... I can no longer repeat it in the symfony-demo, by using the same conditions as before.

Does this sound familiar to anyone? I feel like I'm losing my mind... :)

**Comment by mssimi** [comment]
> And now suddenly... I can no longer repeat it in the symfony-demo, by using the same conditions as before.

@weaverryan Hey, I had same problem, but I noticed it is caused by cache:)

**Comment by weaverryan** [comment]
We should close then. It seems like this is an issue where you might have bad behavior temporarily, but then is fixed when you clear your cache.
