### ISSUE TITLE
Unable to find template

### ISSUE THREAD

**Issue by 128keaton** [sensiolabs/SensioFrameworkExtraBundle#538]
Since pull #508, we've experteinced the error 'Unable to find template'. It appears [here](https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/508/files#diff-7cb1d2e06b631ebdc3c5471e12211ff9R70) that `strtolower` is used. Why was this done without notice in the first place?

![screenshot from 2017-12-04 14-36-40](https://user-images.githubusercontent.com/1402918/33577631-4e4d5318-d909-11e7-84c2-f0a8f6c580a1.png)

**Comment by iltar** [comment]
Is mentioned in here, though maybe not explicitly enough: [changed template name generation from camelCase to under_score](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/CHANGELOG.md#40)

**Comment by 128keaton** [comment]
@iltar yes, it wasn't noted as a [BC break] at all. What are the options for, say, someone whose app uses a ton of templates with camel case naming schemes. Can we add a fallback statement with a depreciated warning?

**Comment by iltar** [comment]
I can recommend to explicitly define the template names, will make your life a lot easier. I'm not sure if 2 majors later this should still be fixed. It might not have been documented, but BC breaks are perfectly legit between majors.

**Comment by fabpot** [comment]
Indeed, @iltar is right. Major versions allows for BC break (and it was in the CHANGELOG, probably not bold enough, but @iltar's PR will fix it).

**Comment by viion** [comment]
Sorry to bump, is there documentation for this on http://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/index.html ?

Also, how does `::file.html.twig` work now there is no Resource folder in the config? I just get cannot find. 

I also do not get how `XXBundle:Namespace:file` works either since no bundles anymore, is this format gone? So far I am explicitly calling my templates... but this doesn't look nice:

```
@Template("home/index.html.twig")
```

```
{% extends '../base.html.twig' %}
```

Is the `master` documentation out of date? It references Symfony 3.3

**Comment by steve-todorov** [comment]
@fabpot, @iltar I don't exactly see the point of this "fix" introduced in `sensio/framework-extra-bundle >= 4.0`. We were upgrading from Symfony 3.2 to 3.4 to prepare for adopting 4.0 early next year and I wasted more than an hour debugging the kernel and twig template engine trying to figure out what's wrong. Our project is huge and we can't magically change all of the template files/paths just because somebody decided they don't like camelCase anymore and "it's is annoying" (quoting some people in #303 and  [symfony-docs#2515](https://github.com/symfony/symfony-docs/issues/2515)). This is just unacceptable. 

PR #507 is introducing more issues for us than it claims to be solving/fixing. I believe there should be a way to configure this and have both `camelCase` and `under_score` so that people can choose what they prefer. I vote to re-open #303. Until then, it appears we'll have to be using an older version of the [TemplateGuesser (v3.0.2)](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v3.0.2/Templating/TemplateGuesser.php#L25).

**Comment by 128keaton** [comment]
@steve-todorov thank you for stating this--our project is similar but we've decided to bite the bullet and move forward away from the older notation. I agree with you though, it is extremely frustrating to change something because "it tastes icky" to one person.

**Comment by steve-todorov** [comment]
@128keaton yeah.. It's kind of funny and illogical IMHO. All of the classes are following CamelCase due to the well known PSR standards and pretty much everything else is following it as well, but only the templates are now forced to be under_score. This makes no sense to me at all.

Anyway, I've fixed my issues by slightly modifying the `TemplateGuesser`. If anybody is interested - feel free to use my ([gist](https://gist.github.com/steve-todorov/0797d3764f1ace60e8fff393365d947d)) - hope it saves you hours in wandering around..

**Comment by iltar** [comment]
> We were upgrading from Symfony 3.2 to 3.4 to prepare for adopting 4.0 early next year and I wasted more than an hour debugging the kernel and twig template engine trying to figure out what's wrong.

Considering this bundle is not part of the core framework, it shouldn't have broken unless you also upgraded this bundle. If you _did_ upgrade this bundle, then you should read the changes carefully (hence I made a PR to make it more clear). This RFC should make it better in the future though: [[RFC] Move annotations from SensioFrameworkExtraBundle to Symfony core](https://github.com/symfony/symfony/issues/25361)

The recommended standard for the template names has always been `foo/foo_bar.html.twig`, so this was actually an existing issue. That being said, using `@Template` is not the recommended way of using the view either. I personally still use it and yes, it will also break for some of my applications. However, due to this guessing being fragile in the first place, I've started to explicitly define the path myself for several years now.

If you really don't want to manually define it (really, you should just do it), you can always stay on 3.0 of this bundle.

**Comment by steve-todorov** [comment]
@iltar yes we'll start using paths to the templates from now on and gradually stop relaying on the guesser for the template paths.

**Comment by viion** [comment]
Does this mean no more of this?

- `::base.html.twig`
- `Namespace:Entity:filename.html.twig`

Instead to the explicit?

**Comment by althaus** [comment]
It still sucks that it's not stated anywhere in clear words. I just copied the updated deps from Symfony Standard 3.4 and it blew up my app. I tried to downgrade the bundle, but this somehow breaks the profiler.

**Comment by iltar** [comment]
@tristanbes There are no UPGRADE file available for this bundle and it's listed in the CHANGELOG now:
![image](https://user-images.githubusercontent.com/1754678/33887671-d53e82f6-df4a-11e7-9ddc-e0a92929170d.png)

If you really want to keep the old system, you can choose to remain on 3.0 for the time being. 

@althaus that's not how you should be upgrading to the next Symfony version though, you should fix _your_ constraints, not use someone else's dependencies as they might not work for you.

**Comment by fabpot** [comment]
You should expect BC breaks when moving from one major version to the next. I don't think we could have done better here.

If someone wants to work on an option to re-enable the old behavior for such cases, I would happily merge the pull request and make a new request to ease migration.

**Comment by althaus** [comment]
@iltar I know that's something you shouldn't do, but my experience told me, that it's most of the time the easiest start to upgrade w/o the need to go through each dep one by one as the standard edition's set of base deps "normally" just works. Never expected such a trapdoor hidden inside.

@fabpot Yes, but I'd somehow had expected a really big warning sign for such a massive BC break or at least an option to control the new behaviour. My personal friend `choices_as_values` did the same without forcing people to change their code immediately. I started with a smaller project for the 3.4-path, where I just had to rename a couple of files.... but we've got a massive software which'll require renaming 100+ files and updates of dozens of separate bundles/modules in sync. I'll be a plain nightmare. 

On a side note: PhpStorm now complains about missing templates due to the plugin not being updated yet. The change wasn't note there quick enough, too. 😢 

So I'd be happy, if someone could come up with an interims solution.

**Comment by iltar** [comment]
I would suggest the following:
 - Put an interface on the class, make a PR for this
 - Once merged, pull the old version out of git, decorate it with the new resolver. If it can't find the template, fall back to the old one and throw a deprecation (could optionally be part of the PR as well).

This way you can get it back to work.

**Comment by althaus** [comment]
Thanks for the idea. I'll try to commit some work in the new year, if the issue isn't resolved then.

**Comment by chetzel** [comment]
Arggghh, same here: hundreds of folders and files must be renamed and not a single comment in the symfony blog or in the "living-on-the-edge" posts! :-(

Before you start to rename the files and folders by hand, you can use this simple bash one-liner to rename the folders in your bundles (and use a similar approach for the files):

    for i in `find . -type d -path "*Resources/views"`; do cd $i; for j in `ls`; do mv $j `echo $j|sed -r 's/([A-Z])/_\l\1/g'|sed -r 's/^_//'`; done; cd -; done

This finds all the "views" folders in your bundles and replaces the capital letters by "_<lowercase letter>" and removes leading underscores in case your folder started with a captial  letter.

**Comment by dspiegel** [comment]
Wow, Just spent all day trying to figure out why all twig paths stopped working after updating from 3.3 to 3.4. Is that considered a major rev? I would think going from 3 to 4 would be major. My application also broke looking for missing _container.build_id_ in ParameterBag.php.

Kind get tired hearing how Symfony can always be trusted to be BC, but over and over I find myself changing major parts of project to get it to work with each minor version. Our team has many Symfony projects with many twig files that now all need to be changed to work in latest versions. 

Just **WOW**, it boggles the mind..... causing everyone out there to spend hours or days to change something which now seems backwards. Naming convention now makes no sense as there is no longer a relation between the controller method and it's associated template. 

`This change should have at least been something that can be controlled with a Twig config parameter in case the programmer doesn't want to uproot the entire view folder, all code using it and database tables storing view information for menus.
`

My boss is going to love this when I tell her all of her programmers will need to spend an extra day or more making changes to working code and testing all functionality before each application can be updated to 3.4 LTS.

**Comment by xabbuh** [comment]
The BC break is not in Symfony, but in SensioFrameworkExtraBundle which you apparently also updated from version 3 to 5 (which means there was a bump in the major version which allows breaking changes).

**Comment by iltar** [comment]
> Kind get tired hearing how Symfony can always be trusted to be BC, but over and over I find myself changing major parts of project to get it to work with each minor version.

30+ applications here, never had that problem since 2.5, not sure why you _do_ have that problem. Perhaps you can document those cases to see if there's anything to improve in the process with Symfony?

> Wow, Just spent all day trying to figure out why all twig paths stopped working after updating from 3.3 to 3.4. Is that considered a major rev?

If you'd have read this issue and check the repository name, you would have seen how or what.

**Comment by aggrosoft** [comment]
I know that major versions allow breaking changes, but would you accept a pull request which makes this behaviour optional? We have exactly the same problem, and from what I see making an option of this would be trivial.

@steve-todorov how did you configure your app to use this, I tried using a compiler pass but maybe I'm doing it wrong:

```
<?php

namespace My\Bundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class OverrideServiceCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('sensio_framework_extra.view.guesser');
        $definition->setClass('My\Bundle\Listener\TemplateGuesser');
    }
}
```

**Comment by althaus** [comment]
@aggrosoft See this comment from iltar with his suggestion to "fix" this. I just hadn't time to spare and we're still using the old version.

https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/538#issuecomment-351326214

**Comment by elonmir** [comment]
@aggrosoft Compiler pass works, just implemented in on our project. Feels quite dirty though... :D

**Comment by AbdenbiWorks** [comment]
// Case if you want to include it:
    {{ include('@Blog/partials/header.html.twig') }} //Blog is the name of bundle
// Case you want extends it:
   {% extends "base.html.twig" %} //From app folder
  {% extends "@Blog/base.html.twig" %} // from Blog Bundle

**Comment by elonmir** [comment]
How about not necroing tickets, would be nice ;)

**Comment by imadetouil** [comment]
the best Solution is 💯 worked thanks  **#@Brush**

// Case if you want to include it:
{{ include('@Blog/partials/header.html.twig') }} //Blog is the name of bundle
// Case you want extends it:
{% extends "base.html.twig" %} //From app folder
{% extends "@Blog/base.html.twig" %} // from Blog Bundle

**Comment by imadetouil** [comment]
thanks @AbdenbiWorks
