### ISSUE TITLE
Invalid option(s) passed to @ParamConverter: format

### ISSUE THREAD

**Issue by piotrantosik** [sensiolabs/SensioFrameworkExtraBundle#542]
After upgrading SF 3.3 to 3.4:

```Invalid option(s) passed to @ParamConverter: format```

Issue is described by https://github.com/kroshp on https://github.com/symfony/symfony/issues/25320
I don't have free time to fully invigistate but probably converter order is invalid - ParamConverterManager should first try apply DateTimeConverter

**Comment by steve-todorov** [comment]
I'm also experiencing this issue after upgrading from 3.2 to 3.4. I am not sure if the order is invalid. From what I can see in the debugger, the issue is somewhere in the [DateTimeParamConverter.php#L35)](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Request/ParamConverter/DateTimeParamConverter.php#L35). Once it goes there the `$request->attributes` ->has()` check fails because the `$request->attributes` is an empty array thus results in `return false` and that then throws the exception. Not sure why this is happening.

**Comment by piotrantosik** [comment]
Bug is here:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Request/ParamConverter/DoctrineParamConverter.php#L291
before check for extra params don't exist
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/3.0/Request/ParamConverter/DoctrineParamConverter.php#L219

**Comment by Ousret** [comment]
Any news about this issue ?

**Comment by alegout** [comment]
+1

**Comment by fnagel** [comment]
+1
