### ISSUE TITLE
Deprecate the @Template annotation?

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioFrameworkExtraBundle#641]
As proposed by @fabpot in [this comment](https://github.com/symfony/symfony-docs/pull/12387#discussion_r329551967) we may consider deprecating the `@Template` annotation.

We always recommended to **not** use it because:

1. It involves some "magic" (not exactly magic, but "hidden conventions");
2. It's common to use `@Template` without any parameters, which makes it more difficult to know which template is being rendered.

Thanks.

**Comment by stof** [comment]
note that it has "magic" only when used without specifying a template name IIRC.

**Comment by romaricdrigon** [comment]
I had the impression there was also a minor performance penalty, isn't it?
It also makes using PHP7 return types inconvenient, since your controller action can sometimes return a `Response` (for instance, a `RedirectResponse`) sometimes an array for `@Template`. 

Since best practices were published, I stopped using it.

**Comment by linaori** [comment]
I like the feature for most of the things. I do prefer a responder over this annotation, though I have used this a lot. I would only like to see the template name guess and implicit parameter passing deprecated. Meaning:
 - It's now mandatory to pass the template name.
 - It will no longer implicitly assign the request attributes in certain scenarios.

Unless Symfony can provides a responder, in that scenario I wouldn't mind `@Template` being deprecated, as a responder would fully replace all functionality and provide more. 

> I had the impression there was also a minor performance penalty, isn't it?
Very, very minor. Some performance issues were already tackled.

**Comment by ciaranmcnulty** [comment]
It is a little too magic, I like @linaori's idea to make the template name mandatory

There is a controller style I used a few years ago (I've since moved away from) that leans heavily on Argument Resolvers (formerly ParamConverters) and the Template annotation to try and give controllers a simpler signature

```
function myController ( SomeValueObject $foo, SomeEntity, $bar) : array
```

This is considerably easier to unit test with mocked entities etc, rather than tying to HttpFoundation and having to test the Controller alongside Twig

I don't really use this style any more but it's worth mentioning because I've seen it in the wild a few times

**Comment by TomasVotruba** [comment]
How is this going? 

<br>

Btw, it's already covered in Rector:

https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#templateannotationrector

![image](https://user-images.githubusercontent.com/924196/84067629-f0b1ed80-a9c7-11ea-9090-f53b3dcf0fa6.png)
