### ISSUE TITLE
@Security annotation evaluation not working as expected

### ISSUE THREAD

**Issue by massimilianobraglia** [sensiolabs/SensioFrameworkExtraBundle#653]
Hello there!

After upgrading to Symfony 4.4 (in particular 4.4.1) from Symfony 4.3.8 the security annotation expressions in my controllers stopped working as expected. I saw the deprecation notices about using an array, but that's not my use case.

What happened:
```php
<?php declare(strict_types=1);

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MyController extends AbstractController
{
    /**
     * @Route(path="/items", methods={"POST"})
     *
     * @Security("is_granted('ROLE_ADMIN')")
     * @IsGranted("ROLE_ADMIN")
     */
    public function postItemAction(Request $request): Response
    {
       // code...
    }
}
```

If the `@IsGranted` annotation is used the `ROLE_ADMIN` is checked with the `RoleHierarchyVoter` and everything is fine. If the `@Security` annotation is used, the expression is not checked.

Am I missing something?

Thanks for your help 😄

**Comment by zghib** [comment]
Here my 5 cents on this
Please see below my investigations:

The problem is that after upgrade the SecurityListener from SensioFrameworkExtraBundle is removed from the container
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/src/DependencyInjection/Compiler/OptimizerPass.php#L26
`if (!$container->hasDefinition('security.token_storage')) {
            $container->removeDefinition('sensio_framework_extra.security.listener');
        }`
The root cause here is security.token_storage which after update became an alias and $container->hasDefinition() doesn't look through aliases.
The result of container debugging 4.3
`bin/console debug:autowiring | grep TokenStorage
 The TokenStorageInterface.
 Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface (security.token_storage)`
in 4.4.1
`bin/console debug:autowiring | grep TokenStorage
 The TokenStorageInterface.
 Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface (security.untracked_token_storage)`

And the key in 4.4.1 is declared as alias
bin/console debug:container | grep security.token_storage
  security.token_storage                                                               alias for "security.untracked_token_storage"

And the question, who is going to fix this?

**Comment by zghib** [comment]
I think here are some misunderstandings between sensio and  symfony/security-bundle as they deprecated
security.token_storage which is pointed to UsageTrackingTokenStorage  
https://github.com/symfony/security-bundle/blob/master/Resources/config/security.xml#L22
So for sensio it will be better to not rely on this key.

Another point is that on a fresh project with symfony 4.4.2 and sensio 5.5.2 I have in container security.token_storage and @Security annotation work as expected.

Will continue investigation to find what is wrong with my container to find why instead of security.token_storage it takes security.untracked_token_storage as everywhere I use TokenStorageInterface

**Comment by xabbuh** [comment]
Can you confirm that #656 fixes the issue?

**Comment by zghib** [comment]
> Can you confirm that #656 fixes the issue?

It works
:+1:
